version: "3"
volumes:
  db-store:
  php-fpm-socket:
services:
  app:
    build: ./line-mytle/php
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ../:/work/laravel

  web:
    build: ./line-mytle/nginx
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ../:/work/laravel

  db:
    build: ./line-mytle/mysql
    volumes:
      - db-store:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=admin
      - PMA_PASSWORD=pass
    volumes:
      - ./line-mytle/phpmyadmin/sessions:/sessions
