name: Laravel CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: administrator
          MYSQL_DATABASE: database
          MYSQL_USER: admin
          MYSQL_PASSWORD: pass
        ports:
          - 3371:3306

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        extension: mbstring, mysql
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: docker-compose build
      run: docker-compose build --no-cache
    - name: docker-compose up -d
      run: docker-compose up -d
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Migrate Database
      run: |
        php artisan migrate
        php artisan db:seed --class=DatabaseSeeder
      env:
        DB_HOST: 127.0.0.1
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: |
        php artisan test
